# Generated by Django 5.2 on 2025-05-16 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingBetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_id', models.IntegerField()),
                ('event_id', models.CharField(max_length=30)),
                ('market_id', models.CharField(max_length=30)),
                ('runner_id', models.CharField(max_length=30)),
                ('side', models.CharField(max_length=4)),
                ('odd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('matched', 'matched'), ('matched_closed', 'matched_closed')], default='waiting', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='EventIdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(choices=[('back', 'back'), ('lay', 'lay')], max_length=4)),
                ('is_open', models.BooleanField(default=True)),
                ('event_id', models.CharField(max_length=25)),
                ('market_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MatchupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_matchup', models.CharField()),
                ('matchup_name', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=30)),
                ('is_running', models.BooleanField(default=False)),
                ('team_a', models.CharField(max_length=30)),
                ('team_b', models.CharField(max_length=30)),
                ('time_elapsed', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_id', models.IntegerField()),
                ('event_id', models.CharField(max_length=30)),
                ('market_id', models.CharField(max_length=30)),
                ('runner_id', models.CharField(max_length=30)),
                ('side', models.CharField(max_length=4)),
                ('odd', models.DecimalField(decimal_places=4, max_digits=8)),
                ('stake', models.DecimalField(decimal_places=4, max_digits=8)),
                ('responsabilidade', models.DecimalField(decimal_places=4, max_digits=8)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('matched', 'matched'), ('matched_closed', 'matched_closed')], default='waiting', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='SessionsBolsaApostaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biab_customer', models.CharField(max_length=500)),
                ('authorization', models.CharField(max_length=500)),
                ('sb', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MarketIdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.CharField(max_length=50)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.eventidmodel')),
            ],
        ),
    ]
