# Generated by Django 5.2 on 2025-04-20 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApostaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=30)),
                ('market_id', models.CharField(max_length=30)),
                ('runner_id', models.CharField(max_length=30)),
                ('side', models.CharField(max_length=4)),
                ('odd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('matched', 'matched'), ('matched_closed', 'matched_closed')], default='waiting', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='ClosingBetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=30)),
                ('market_id', models.CharField(max_length=30)),
                ('runner_id', models.CharField(max_length=30)),
                ('side', models.CharField(max_length=4)),
                ('odd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('matched', 'matched'), ('matched_closed', 'matched_closed')], default='waiting', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=30)),
                ('market_id', models.CharField(max_length=30)),
                ('runner_id', models.CharField(max_length=30)),
                ('side', models.CharField(max_length=4)),
                ('odd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('matched', 'matched'), ('matched_closed', 'matched_closed')], default='waiting', max_length=14)),
                ('closer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.closingbetmodel')),
            ],
        ),
    ]
