# Generated by Django 5.2 on 2025-04-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_apostamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(choices=[('back', 'back'), ('lay', 'lay')], max_length=4)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
