# Generated by Django 5.2 on 2025-05-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sessionsbolsaapostamodel_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionsbolsaapostamodel',
            name='authorization',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sessionsbolsaapostamodel',
            name='biab_customer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sessionsbolsaapostamodel',
            name='device_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sessionsbolsaapostamodel',
            name='sb',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
