# Generated by Django 5.2 on 2025-04-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_flowmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchup_name', models.CharField(max_length=150)),
                ('id_matchup', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('sport', models.CharField(max_length=30)),
                ('is_running', models.BooleanField(default=False)),
                ('team_a', models.CharField(max_length=30)),
                ('team_b', models.CharField(max_length=30)),
                ('time_elapsed', models.CharField(max_length=30)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
            ],
        ),
    ]
