# Generated by Django 5.2 on 2025-05-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_sessionsbolsaapostamodel_authorization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_id', models.IntegerField()),
                ('event_id', models.CharField(max_length=30)),
                ('market_id', models.CharField(max_length=30)),
                ('runner_id', models.CharField(max_length=30)),
                ('side', models.CharField(max_length=4)),
                ('odd', models.DecimalField(decimal_places=4, max_digits=8)),
                ('stake', models.DecimalField(decimal_places=4, max_digits=8)),
                ('stake_matched', models.DecimalField(decimal_places=4, max_digits=8)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('matched', 'matched'), ('matched_closed', 'matched_closed')], default='waiting', max_length=14)),
            ],
        ),
        migrations.DeleteModel(
            name='ClosingBetModel',
        ),
        migrations.DeleteModel(
            name='FlowModel',
        ),
        migrations.DeleteModel(
            name='OpeningBetModel',
        ),
    ]
