# Generated by Django 5.2 on 2025-04-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_matchupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchupmodel',
            name='away_score',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='matchupmodel',
            name='home_score',
            field=models.CharField(max_length=30),
        ),
    ]
