# Generated by Django 5.2 on 2025-05-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_betmodel_delete_closingbetmodel_delete_flowmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='betmodel',
            name='partial_stake',
            field=models.DecimalField(decimal_places=4, default=2, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='betmodel',
            name='bet_id',
            field=models.CharField(max_length=30),
        ),
    ]
