# Generated by Django 5.2 on 2025-05-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_betmodel_created_at_betmodel_partial_stake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betmodel',
            name='liquidity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='betmodel',
            name='odd',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='betmodel',
            name='partial_stake',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='betmodel',
            name='stake',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='betmodel',
            name='stake_matched',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
