# Generated by Django 5.2 on 2025-04-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_matchupmodel_away_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchupmodel',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='matchupmodel',
            name='home_score',
        ),
    ]
