# Generated by Django 5.2 on 2025-06-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_betmodel_liquidity_alter_betmodel_odd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeDefaultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=8, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='betmodel',
            name='liquidity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
