# Generated by Django 5.2 on 2025-04-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_matchupmodel_away_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionsBolsaApostaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biab_customer', models.CharField(max_length=500)),
                ('authorization', models.CharField(max_length=500)),
                ('sb', models.CharField(max_length=500)),
            ],
        ),
    ]
