# Generated by Django 5.2 on 2025-05-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sessionsbolsaapostamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowmodel',
            name='event_id',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowmodel',
            name='market_id',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
