# Generated by Django 5.2 on 2025-05-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_flowmodel_event_id_flowmodel_market_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingbetmodel',
            name='closer',
        ),
        migrations.AddField(
            model_name='openingbetmodel',
            name='responsabilidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
